helpme/urls.py
from django.urls import path

from helpme import views

app_name = "helpme"

urlpatterns = [
    path("", views.SupportDashboardView.as_view(), name="dashboard"),
    path("faq/", views.FAQView.as_view(), name="faq"),
    path("faq/create/", views.FAQCreateView.as_view(), name="faq-create"),
    path("request/", views.SupportRequestView.as_view(), name="submit-request"),
    path("ticket/<uuid:uuid>/", views.TicketDetailView.as_view(), name="ticket-detail"),
    path("teams/", views.TeamCreateView.as_view(), name="team-list"),
    path("teams/<uuid:uuid>/", views.TeamDetailView.as_view(), name="team-detail"),
]

helpme/models.py
import uuid 
import datetime

from multiselectfield import MultiSelectField

from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager

from .settings import app_settings


##################
# CHOICES
##################


class StatusChoices(models.IntegerChoices):
    OPEN = 1, _("Open")
    ACTIVE = 10, _("Active")
    HOLD = 20, _("Hold")
    CLOSED = 30, _("Closed")
    CANCELED = 40, _("Canceled")

class PriorityChoices(models.IntegerChoices):
    SUGGESTION = 1, _("Suggestion")
    LOW = 2, _("Low")
    MEDIUM = 3, _("Medium")
    HIGH = 4, _("High")
    URGENT = 5, _("Urgent")

class VisibilityChoices(models.IntegerChoices):
    REPORTERS = 1, _("Reporters")
    SUPPORT = 10, _("Support Handlers")
    DEVELOPERS = 15, _("Developers")
    SUPERVISORS = 20, _("Supervisors")

class CommentTypeChoices(models.IntegerChoices):
    MESSAGE = 0, _('Message')
    EVENT = 1, _('Event')


##################
# ABSTRACT MODELS
##################

class CreateUpdateModelBase(models.Model):
    created = models.DateTimeField("date created", auto_now_add=True)
    updated = models.DateTimeField("last updated", auto_now=True)

    class Meta:
        abstract = True

    def been_updated(self):
        return (self.updated - self.created) > datetime.timedelta(seconds=1)
    
##################
# MODELS
##################

class Category(models.Model):
    category = models.CharField(_("Category"), max_length=120)
    category_sites = models.ManyToManyField(Site, blank=True, related_name="categories")
    localization = models.JSONField(default=dict)
    global_category = models.BooleanField(default=False)
    category_excluded_sites = models.ManyToManyField(Site, blank=True, related_name="excluded_categories")

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category


class Question(models.Model):
    question = models.CharField(_("Question"), max_length=120)
    answer = models.CharField(_("Answer"), max_length=255)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, related_name="questions")
    sites = models.ManyToManyField(Site, blank=True, related_name="questions")
    localization = models.JSONField(default=dict)
    global_question = models.BooleanField(default=False)
    excluded_sites = models.ManyToManyField(Site, blank=True, related_name="excluded_questions")

    def __str__(self):
        return self.question
    

class Team(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(_("Name"), max_length=30)
    global_team = models.BooleanField(default=False)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    sites = models.ManyToManyField(Site)
    categories = MultiSelectField(_("Categories"), choices=app_settings.TICKET_CATEGORIES.choices)

    def __str__(self):
        return self.name
    

class Ticket(CreateUpdateModelBase):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    status = models.IntegerField(_("Status"), default=StatusChoices.OPEN, choices=StatusChoices.choices)
    priority = models.IntegerField(_("Priority"), default=PriorityChoices.MEDIUM, choices=PriorityChoices.choices)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="support_tickets")
    user_meta = models.JSONField(blank=True, null=True, default=dict)
    category = models.IntegerField(_("Category"), choices=app_settings.TICKET_CATEGORIES.choices)
    teams = models.ManyToManyField(Team, blank=True, related_name="support_tickets")
    subject = models.CharField(_("Subject"), max_length=120)
    description = models.TextField(_("Message"))
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="assigned_tickets")
    dev_ticket = models.CharField(_("Developer Ticket"), max_length=30, blank=True, null=True)
    related_to = models.ManyToManyField("self", blank=True)
    site = models.ForeignKey(Site, default=1, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, blank=True, null=True, on_delete=models.SET_NULL)

    objects = models.Manager() 
    on_site = CurrentSiteManager()

    class Meta:
        permissions = (
            ("see_support_tickets", "Access to support-level tickets"), 
            ("see_developer_tickets", "Access to developer-level tickets"), 
            ("see_all_tickets", "Access to all tickets"),
        ) 

    def __str__(self):
        if self.user:
            return "{0} - {1}".format(self.user.username, self.subject)
        elif self.user_meta.get("full_name"):
            return "{0} - {1}".format(self.user_meta["full_name"], self.subject)
        else:
            return "{0}".format(self.subject)

    def log_history_event(self, action, user=None, notes=None, isotime=None):
        '''
        "history": [
            {
                "time": "2020-04-08T23:45:02.225609+00:00",
                "action": "created"
            }
        ],
        '''
        if not isotime:
            isotime = timezone.now().isoformat()           # '2019-12-18T22:27:28.222000+00:00'

        event = {'action':action, 'time':isotime}

        if user:
            event['user'] = user.pk
            event['username'] = user.username

        if notes:
            event['notes'] = notes

        self.history.append(event)

    
class Comment(CreateUpdateModelBase):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    content = models.TextField(_("Content"))
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name="comments")
    visibility = models.IntegerField(_("Visibility"), default=VisibilityChoices.REPORTERS, choices=VisibilityChoices.choices)
    comment_type = models.IntegerField(_("Type"), default=CommentTypeChoices.MESSAGE, choices=CommentTypeChoices.choices)

    def __str__(self):
        return "{0} - {1}".format(self.user.username, self.created)
    

helpme/forms.py
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.sites.models import Site
from django.contrib.auth import get_user_model

from helpme.models import Ticket, Comment, Category, Question, Team, VisibilityChoices
from helpme.utils import get_current_site


class AnonymousTicketForm(ModelForm):
    full_name = forms.CharField(label=_("Full Name"), widget=forms.TextInput(attrs={"placeholder": _("Enter name")}))
    email = forms.EmailField(label=_("Email Address"), widget=forms.EmailInput(attrs={"placeholder": _("Enter email")}))
    phone_number = forms.CharField(label=_("Phone Number (Optional)"), required=False)
    
    class Meta:
        model = Ticket
        fields = ['full_name', 'email', 'phone_number', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].label = _("How Can We Help You?")
        self.fields['description'].widget.attrs.update({'placeholder': _('Enter Message'), 'rows': 4})

        
class TicketForm(ModelForm):

    class Meta:
        model = Ticket
        fields = ['category', 'subject', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs.update({'placeholder': _('Enter Subject Title')})
        self.fields['description'].widget.attrs.update({'placeholder': _('Enter Details')})


class UpdateTicketForm(ModelForm):
    teams = forms.ModelMultipleChoiceField(queryset=Team.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)

    class Meta:
        model = Ticket
        fields = ['status', 'priority', 'category', 'teams', 'assigned_to', 'dev_ticket', 'question']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dev_ticket'].label = _("Developer Ticket")
        self.fields['question'].label = _("Related Frequently Asked Question")
        self.fields['assigned_to'].label = _("Assigned to")
        self.fields['teams'].label = _("Teams")
        
        # filter teams by those that are responsible for the site where the ticket was created
        self.fields['teams'].queryset = Team.objects.filter(sites__in=[self.instance.site])


class CommentForm(ModelForm):
    content = forms.CharField(label=_("Message"), widget=forms.Textarea(attrs={'placeholder': _('Enter a message'), 'rows': '4'}))
    visibility = forms.ChoiceField(label=_("Visibility (Who can see this message)"), choices=VisibilityChoices.choices)
    
    class Meta:
        model = Comment
        fields = ['content', 'visibility']

    def __init__(self, support=True, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not support:
            self.fields.pop('visibility')
            

class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ['category']


class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = ['question', 'answer', 'category']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

        # limit the possible categories to the current site
        current_site = get_current_site(self.request)
        self.fields['category'].queryset = Category.objects.filter(category_sites__in=[current_site])
        self.fields['category'].label = _("Category")


class TeamForm(ModelForm):
    # get users with explicit support permissions
    # as well as admins with all permissions
    member_qs = get_user_model().objects.filter(user_permissions__codename="see_support_tickets") | get_user_model().objects.filter(is_superuser=True)
    members = forms.ModelMultipleChoiceField(queryset=member_qs.distinct(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Team
        fields = ['name', 'categories', 'members']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['members'].label = _("Members")


class SupportEmailForm(forms.Form):
    email = forms.EmailField(label=_("Support Email"), required=False)

helpme/templates/helpme/anonymous_ticket.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block help_content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{% trans 'Send' %}" class="btn btn-primary">
</form>
{% endblock %}

helpme/templates/helpme/base.html
{% extends "base.html" %}

{% block content %}

{% block help_content %}
{% endblock %}

{% endblock %}

helpme/templates/helpme/faq.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block help_content %}

<div class="container-fluid">
    <div class="row no-gutters">
	<h1> {% trans "HELP DESK" %} </h1>
    </div>
    <div class="row no-gutters">
	<a href="{% url 'helpme:faq' %}" class="mr-3">
	    <h5 class="text-dark">
		<u> {% trans "FAQ" %} </u>
	    </h5>
	</a>
	<a href="{% url 'helpme:dashboard' %}" class="ml-3">
	    <h5>{% trans "ASK THE HELP DESK" %}</h5>
	</a>
    </div>

    <div class="row">
	{% for category in categories %}
	<div class="col-sm-4 my-3">
	    <h5>
		<b>
		    {{ category }}
		</b>
	    </h5>
	    {% for question in category.questions.all %}
	    <p>
		<a class="question" data-toggle="collapse" href="#answer-{{question.pk}}">
		    {{ question.question }}
		</a>
	    </p>
	    <p class="collapse" id="answer-{{question.pk}}">
		{{ question.answer }}
	    </p>
	    <hr>
	    {% empty %}
	    {% trans "There are no Frequently Asked Questions in this category yet." %}
	    {% endfor %}
	</div>
	{% empty %}
	{% for question in questions %}
	<div class="col-sm-4 my-3">
	    <p>
		<a class="question" data-toggle="collapse" href="#answer-{{question.pk}}">
		    {{ question.question }}
		</a>
	    </p>
	    <p class="collapse" id="answer-{{question.pk}}">
		{{ question.answer }}
	    </p>
	</div>
	{% empty %}
	<div class="col my-3">
	    {% trans "There are no Frequently Asked Questions yet." %}
	</div>
	{% endfor %}
	{% endfor %}
    </div>

</div>
{% endblock %}
  
{% block extra_js %}
<!-- A question becomes bold when selected -->
<script>
  var questions = document.getElementsByClassName('question');
  var num = questions.length;
  
  function toggleBold(e) {
    var question = $(e.currentTarget)[0];
  
    if (question.style.fontWeight === "bold") {
      question.style.fontWeight = ""
    }
    else {
      question.style.fontWeight = "bold"
    }
  }

  for (var i = 0; i < num; i++) {
    questions[i].addEventListener('click', toggleBold, false)
  };
</script>
{% endblock %}

helpme/templates/helpme/faq_create.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block help_content %}

<div class="container-fluid">
    <div class="row">
	{% for category in categories %}
	<div class="col-sm-4 my-3">
	    <h5>
		<b>
		    {{ category }}
		</b>
	    </h5>
	    {% for question in category.questions.all %}
	    <p>
		<a class="question" data-toggle="collapse" href="#answer-{{question.pk}}">
		    {{ question.question }}
		</a>
	    </p>
	    <p class="collapse" id="answer-{{question.pk}}">
		{{ question.answer }}
	    </p>
	    <hr>
	    {% empty %}
	    {% trans "There are no Frequently Asked Questions in this category yet." %}
	    {% endfor %}
	</div>
	{% empty %}
	{% for question in questions %}
	<div class="col-sm-4 my-3">
	    <p>
		<a class="question" data-toggle="collapse" href="#answer-{{question.pk}}">
		    {{ question.question }}
		</a>
	    </p>
	    <p class="collapse" id="answer-{{question.pk}}">
		{{ question.answer }}
	    </p>
	</div>
	{% empty %}
	<div class="col my-3">
	    {% trans "There are no Frequently Asked Questions yet." %}
	</div>
	{% endfor %}
	{% endfor %}
    </div>

    {% if perms.helpme.add_category %}
    <div class="my-3">
	<h3> {% trans "Create a New Category" %} </h3>
	<div class="row">
	    <div class="col-sm">
		<form method="post" id="category_form" action="{% url 'helpme-api-create-category' %}">
		    {% csrf_token %}
		    {{ category_form|crispy }}
		    <input type="submit" value="{% trans 'Create' %}" class="btn btn-primary font-weight-bold px-4 py-2 rounded-pill">
		</form>
	    </div>
	</div>
    </div>
    {% endif %}

    {% if perms.helpme.add_question %}
    <div class="mt-3">
	<h3> {% trans "Create a New Question" %} </h3>
	<div class="row">
	    <div class="col-sm">
		<form method="post" id="question_form" action="{% url 'helpme-api-create-question' %}">
		    {% csrf_token %}
		    {{ question_form|crispy }}
		    <input type="submit" value="{% trans 'Create' %}" class="btn btn-primary font-weight-bold px-4 py-2 rounded-pill">
		</form>
	    </div>
	</div>
    </div>
    {% endif %}
  
</div>
{% endblock %}
  
{% block extra_js %}
<!-- A question becomes bold when selected -->
<script>
  var questions = document.getElementsByClassName('question');
  var num = questions.length;
  
  function toggleBold(e) {
    var question = $(e.currentTarget)[0];
  
    if (question.style.fontWeight === "bold") {
      question.style.fontWeight = ""
    }
    else {
      question.style.fontWeight = "bold"
    }
  }

  for (var i = 0; i < num; i++) {
    questions[i].addEventListener('click', toggleBold, false)
  };
</script>
{% endblock %}

helpme/templates/helpme/supportrequest_form.html
{% extends "helpme/base.html" %}

{% block help_content %}
<form action="{% url 'helpme-submit-request' %}" method="POST">
{% csrf_token %}
{{ form.as_ul }}
<input type="submit" value="Submit">
</form>
{% endblock %}

helpme/templates/helpme/team_detail.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block help_content %}
{% if admin %}
<h1 class="my-2">{% blocktrans with team=team.name %}Manage {{team}} Team{% endblocktrans %}</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{% trans 'Update' %}" class="btn btn-primary font-weight-bold py-2 px-4 mt-3 rounded-pill">
</form>
<p>
    <b>{% trans "Handles Site(s)" %}: </b>
    <ul class="list-group">
	{% for site in team.sites.all %}
	<li class="list-group-item">
	    {{ site }}
	</li>
	{% endfor %}
    </ul>
</p>
{% else %}
<h1 class="my-2">{{team.name}}</h1>
<p>
    <b>{% trans "Site(s)" %}: </b>
    <ul class="list-group">
    {% for site in team.sites.all %}
        <li class="list-group-item">
            {{ site }}
        </li>
    {% endfor %}
    </ul>
</p>
<p>
  <b>{% trans "Handles Categories" %}: </b>
  {{ team.categories }}
</p>
<p>
    <b>{% trans "Members" %}: </b>
    <ul class="list-group">
	{% for member in team.members.all %}
        <li class="list-group-item">
            {{member}}
        </li>
	{% endfor %}
    </ul>
</p>
{% endif %}
<div class="row justify-content-center mb-2">
    <a class="text-light" href="{% url 'helpme_admin:team-list' %}">
	<button class="btn btn-primary font-weight-bold px-4 py-2 rounded-pill">
	    {% trans "Return to Teams Page" %}
	</button>
    </a>
</div>
{% endblock %}

{% block extra_js %}
<!-- select all sites if global_team is checked; unselect them if it is unchecked -->
<script>
  $("#id_global_team").change(function() {
    checkboxes = document.getElementsByName('sites');
    global = document.getElementById('id_global_team');
    for(var i=0, n=checkboxes.length;i<n;i++) {
      checkboxes[i].checked = global.checked;
    }
  });
</script>
{% endblock %}

helpme/templates/helpme/team_form.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block help_content %}
{% if admin %}

<table class="table table-striped table-bordered text-center mt-2">
    <thead>
	<tr class="bg-info text-white">
	    <th>{% trans "Manage Teams" %}</th>
	</tr>
    </thead>
    <tbody>
	{% for team in teams %}
	<tr>
	    <td class="align-middle">
		<a href="{% url 'helpme_admin:team-detail' team.uuid %}"> {{ team }} </a>
	    </td>
	</tr>
	{% empty %}
	<tr>
	    <td>{% trans "You are not managing any teams yet." %}</td>
	</tr>
	{% endfor %}
    </tbody>
</table>

<h2>{% trans "Create a new team" %}</h2>
<form action="{% url 'helpme_admin:team-list' %}" method="POST" class="mb-2">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{% trans 'Create Team' %}" class="btn btn-primary font-weight-bold py-2 px-4 mt-3 rounded-pill">
</form>

{% else %}
<table class="table table-striped table-bordered text-center my-2">
    <thead>
	<tr class="text-light bg-info">
	    <th>{% trans "My Teams" %}</th>
	</tr>
    </thead>
    <tbody>
	{% for team in user_teams %}
	<tr>
	    <td class="align-middle">
		<a href="{% url 'helpme_admin:team-detail' team.uuid %}"> {{ team }} </a>
	    </td>
	</tr>
	{% empty %}
	<tr>
	    <td>{% trans "You don't belong to any teams yet." %}</td>
	</tr>
	{% endfor %}
    </tbody>
</table>

{% endif %}
{% endblock %}

{% block extra_js %}
<!-- select all sites if global_team is checked; unselect them if it is unchecked -->
<script>
  $("#id_global_team").change(function() {
    checkboxes = document.getElementsByName('sites');
    global = document.getElementById('id_global_team');
    for(var i=0, n=checkboxes.length;i<n;i++) {
      checkboxes[i].checked = global.checked;
    }
  });
</script>
{% endblock %}

helpme/templates/helpme/ticket_detail.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load helpme_extras %}
{% load i18n %}

{% block help_content %}

<div class="container-fluid mt-3">
    <div class="row align-items-end">
	<div class="col">
	    <h3 class="mt-3">
		<b> {{ ticket.subject }} </b>
	    </h3>
	    <div>
		{% trans "Status" %}:
		{% if ticket.status in negative_status %}
		<span class="text-danger mr-2">
		    <b>
			{{ ticket.get_status_display }}
		    </b>
		</span>
		{% else %}
		<span class="text-success mr-2">
		    <b>
			{{ ticket.get_status_display }}
		    </b>
		</span>
		{% endif %}
		{% trans "Priority" %}:
		<b>
		    {{ ticket.get_priority_display }}
		</b>
	    </div>
	    <small>
		{% trans "Created" %}: {{ticket.created}}
	    </small>
	    <div>
		{% trans "Category" %}: <b>{{ ticket.get_category_display  }}</b>
	    </div>
	    <p class="mt-3"> {{ ticket.description }} </p>
	</div>
	<div class="col-sm text-center text-sm-right mb-3">
	    <a href="" role="button" data-toggle="modal" data-target="#edit" class="text-primary font-weight-bold">{% trans "Edit Details" %}</a>
	    <button class="btn btn-primary font-weight-bold rounded-pill px-4 py-2 ml-3"  data-toggle="modal" data-target="#request">
		{% trans "New Help Ticket" %}
	    </button>
	</div>
    </div>
</div>

<hr>

<div class="parent-container d-flex">
    <div class="container" style="width:66%;">
	{% if ticket_comments.exists %}
	<div class="text-primary font-weight-bold dropdown mb-2" id="most_recent">
	    <a role="button" class="dropdown-toggle"> {% trans "Most recent" %} </a>
	</div>
	<div class="container overflow-auto" style="max-height:350px;">
	    {% for comment in ticket_comments %}
    
	    {% if comment in comments %}
	    {% trans "Message" as message %}
	    {% trans "Event" as event %}
	    {% if comment.get_comment_type_display == message %}
    
	    {% if comment.user == user %}
	    <div class="row mb-3">
		<div class="col offset-1">
		    <div class="p-3 alert-primary mb-0 rounded-pill">
			{{ comment.content  }}
		    </div>
		    <small>
			{% trans "Visibility" %}: {{ comment.get_visibility_display }}
		    </small>
		    <small class="float-right">
			<b>{{ comment.user.username }}</b>
			{{ comment.created }}
		    </small>
		</div>
	    </div>
	    {% else %}
	    <div class="row mb-3">
		<div class="col-11">
		    <div class="p-3 alert-secondary mb-0 rounded-pill">
			{{ comment.content  }}
		    </div>
		    <small>
			<b>{{ comment.user.username }}</b>
			{{ comment.created }}
		    </small>
		    <small class="float-right">
			{% trans "Visibility" %}: {{ comment.get_visibility_display }}
		    </small>
		</div>
	    </div>
	    {% endif %}
	
	    {% elif comment.get_comment_type_display == event  %}
	    <div class="row mb-3">
		<div class="col-sm-6 offset-sm-3 text-center">
		    <div>
			{{ comment.content }}
		    </div>
		    <small>
			{{ comment.created }}
		    </small>
		</div>
	    </div>
	    {% endif %}
	    {% endif %}

	    {% endfor %}
	</div>
	{% endif %}
	
	<div class="row">
	    <div class="col">
		<form action="{% url 'helpme-api-create-comment' ticket.uuid %}" method="POST" class="mb-3">
		    {% csrf_token %}
		    {{ comment_form|crispy }}
		    <input type="submit" value="{% trans 'Reply' %}" class="btn btn-primary font-weight-bold rounded-pill px-4 py-2 mr-3">
		</form>
	    </div>
	</div>
    </div>
    <div class="container" style="width:33%;">
	<div class="row">
	    <div class="col-sm">
		<p>
		    <b>{% trans "Reporter" %}: </b>
                    {% if ticket.user %}
		    {{ticket.user.username}}
                    {% else %}
                    {{ ticket.user_meta.full_name }}
                    {% endif %}
		</p>
		<p>
		    {% include "./includes/user_meta.html" with user_meta=ticket.user_meta %}
		</p>
		<p>
		    <b>{% trans "Site" %}: </b>
		    {{ticket.site}}
		</p>
		<p>
		    <b>{% trans "Last Updated" %}: </b>
		    {{ticket.updated}}
		</p>
	    </div>
	</div>
    </div>
</div>
<div class="row justify-content-center my-3">
    <a class="text-light" href="{% url 'helpme_admin:dashboard' %}">
	<button class="btn btn-primary font-weight-bold px-4 py-2 rounded-pill">
	    {% trans "Return to Dashboard" %}
	</button>
    </a>
</div>

<div class="modal" id="request">
    <div class="modal-dialog">
	<div class="modal-content">

	    <!-- Modal body -->
	    <div class="modal-body">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h3 class="modal-title mt-3">
		    <b>{% trans "New Help Ticket" %}</b>
		</h3>
		<p> {% trans "Please provide clear details about how we can help you." %} </p>
		<form action="{% url 'helpme-api-create-ticket' %}" method="POST">
		    {% csrf_token %}
		    {{ ticket_form|crispy }}
		    <input type="submit" value="{% trans 'Create Ticket' %}" class="btn btn-primary font-weight-bold rounded-pill px-4 py-2 mr-3">
		    <a href="" data-dismiss="modal" class="text-primary font-weight-bold">{% trans "Cancel" %}</a>
		</form>
	    </div>
	    
	</div>
    </div>
</div>

<div class="modal" id="edit">
    <div class="modal-dialog">
	<div class="modal-content">

	    <!-- Modal body -->
	    <div class="modal-body">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h3 class="modal-title mt-3">
		    <b>{% trans "Edit Ticket Details" %}</b>
		</h3>
		<form method="post">
		    {% csrf_token %}
		    {{ form|crispy }}
		    <input type="submit" value="{% trans 'Update' %}" class="btn btn-primary rounded-pill font-weight-bold px-4 py-2">
		</form>
	    </div>
	</div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<!-- toggle the dropdown/dropup filter on page reload if it is set to display oldest comments first -->
<script>
  $(document).ready(function() {
  if (localStorage.getItem('dropdown') == 'oldest') {
    var recent = document.getElementById("most_recent");
    recent.classList.toggle("dropdown");
    recent.classList.toggle("dropup");
  }
  });
</script>

<!-- on click, toggle between displaying comments by oldest or most recent -->
<script>
  var recent = document.getElementById("most_recent");
  recent.addEventListener('click', function(event){
    recent.classList.toggle("dropdown");
    recent.classList.toggle("dropup");
    var url = window.location.origin + window.location.pathname;
    if (recent.classList.contains("dropup")){
      localStorage.setItem('dropdown', 'oldest');
      window.location = url + '?oldest';
    }
    else {
      localStorage.setItem('dropdown', 'recent');
      window.location = url;
    }
  });
</script>
{% endblock %}

helpme/templates/helpme/ticket_form.html
{% extends "helpme/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block help_content %}

  <div class="row">
    <div class="col-sm">
      <h1>{% trans "Create a Support Request" %}</h1>
    </div>
    <div class="col-sm">
        <form action="{% url 'helpme:submit-request' %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="{% trans 'Submit' %}" class="btn btn-primary font-weight-bold px-4 py-2 rounded-pill">
        </form>
    </div>
  </div>

{% endblock %}